baseURL = 'https://XBlankZGap.github.io/'
languageCode = 'en-us'
title = "Sophy's Portfolio"
theme = 'PaperMod'

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 60

[params]
    # This combines your footer ideas into one professional line
    footerContent = "Ready for a Security Audit? [Email Me](mailto:your-email@example.com) | [Contact Form](/contact/)"

[markup.goldmark.renderer]
    unsafe = true
